image: python:latest

cache:
  paths:
    - ~/.cache/pip/

stages:
  - test
  - style
  - docs
  - deploy

pep8:
  stage: style
  before_script:
    - pip install -r ci/pycodestyle/requirements.txt
    - chmod +x ci/pycodestyle/runner.sh
  script:
    - ./ci/pycodestyle/runner.sh
  artifacts:
    paths:
      - public/pycodestyle.txt
  only:
    - develop
    - master

pylint:
  stage: style
  before_script:
    - pip install -r ci/pylint/requirements.txt
    - chmod +x ci/pylint/runner.sh
  script:
    - ./ci/pylint/runner.sh
  artifacts:
    paths:
      - public
  only:
    - develop
    - master

test:
  stage: test
  before_script:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt
  script:
    - coverage run manage.py test
    - coverage report --omit=manage.py
    - coverage html --omit=manage.py
    - mkdir public
    - mv htmlcov public/coverage
  artifacts:
    paths:
      - public/coverage
  only:
    - develop
    - master

sphinx:
  stage: docs
  before_script:
    - pip install -r ci/sphinx/requirements.txt
    - chmod +x ci/sphinx/runner.sh
  script:
    - ./ci/sphinx/runner.sh
  artifacts:
    paths:
      - public/docs
  only:
    - develop
    - master

heroku:
  stage: deploy
  before_script:
    - chmod +x ci/heroku/runner.sh
  script:
    - ./ci/heroku/runner.sh
  only:
    - master
