# Generated by Django 3.1.6 on 2021-04-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarsession',
            name='cookie',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
