# Generated by Django 3.1.6 on 2021-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_email',
            field=models.CharField(default='krimiussp@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='service_password',
            field=models.CharField(default='promprog', max_length=255),
        ),
    ]
