# Generated by Django 3.2.2 on 2021-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_webinarsession_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarsession',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
