# Generated by Django 3.1.6 on 2021-03-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210312_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service_password',
        ),
        migrations.AddField(
            model_name='user',
            name='organizationId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sessionId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='webinar_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='webinar_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
