# Generated by Django 3.1.6 on 2021-04-29 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_webinarsession_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fontsize',
            field=models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(48)]),
        ),
    ]
