# Generated by Django 3.1.6 on 2021-02-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_additionaluserinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apikey',
            field=models.CharField(default='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', max_length=32),
        ),
        migrations.DeleteModel(
            name='AdditionalUserInfo',
        ),
    ]
