# Generated by Django 3.2.2 on 2021-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_discordhistory_message_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
