# Generated by Django 3.2.2 on 2021-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_discordhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordhistory',
            name='message_ids',
            field=models.JSONField(default=set),
        ),
    ]
