# Generated by Django 3.2.2 on 2021-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_discordhistory_message_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordhistory',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
