# Generated by Django 3.2.2 on 2021-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_discordhistory_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordhistory',
            name='webhooks',
            field=models.JSONField(default=list),
        ),
    ]
