# Generated by Django 3.2.2 on 2021-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_discordhistory_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordhistory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
